import { ContactLink, Experience, NavNode, Profile, Project, SiteThemeSettings, Skill } from './types';
import { DEFAULT_SITE_THEME } from './theme';

export const NAV_NODES: NavNode[] = [
    { id: 'about', label: 'Perfil', sublabel: '01 - Identidad', gridArea: 'about' },
    { id: 'projects', label: 'Proyectos', sublabel: '02 - Obra', gridArea: 'projects' },
    { id: 'experience', label: 'Trayectoria', sublabel: '03 - Recorrido', gridArea: 'experience' },
    { id: 'skills', label: 'Dominio', sublabel: '04 - Competencias', gridArea: 'skills' },
    { id: 'contact', label: 'Contacto', sublabel: '05 - Conexion', gridArea: 'contact' },
];

export const sampleProfile: Profile = {
    id: 'seed-profile',
    name: 'Clider Fernando Tutaya Rivera',
    title: 'Ingeniero de Software Full Stack',
    bio: 'Desarrollador Full Stack especializado en la creacion de soluciones informaticas escalables y centradas en el usuario. Combino una solida base tecnica en ecosistemas Java, Spring Boot y tecnologias frontend modernas como Vue.js y React para disenar experiencias digitales eficientes y arquitecturas robustas que resuelven problemas del mundo real.',
    location: 'Lima, Peru',
    email: 'clidertutayarivera@gmail.com',
    avatar_url: null,
    avatar_storage_path: null,
    cv_url: null,
    cv_storage_path: null,
    seo_title: 'Clider Fernando - Software Engineer',
    seo_description: 'Portafolio profesional de Clider Fernando Tutaya Rivera. Ingeniero de Software Full Stack especializado en arquitecturas de backend con Spring Boot y frontend interactivo.',
    seo_keywords: 'desarrollador full stack, ingeniero de software, java, spring boot, vue.js, react, portfolio',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
};

export const sampleContactLinks: ContactLink[] = [
    { id: '1', label: 'GitHub', url: 'https://github.com/Nightmarespirits', icon: 'github', sort_order: 0, is_visible: true, created_at: new Date().toISOString() },
    { id: '2', label: 'LinkedIn', url: 'https://linkedin.com/in/clider-fernando-tutaya-rivera-987128300', icon: 'linkedin', sort_order: 1, is_visible: true, created_at: new Date().toISOString() },
    { id: '3', label: 'Email', url: 'mailto:clidertutayarivera@gmail.com', icon: 'email', sort_order: 2, is_visible: true, created_at: new Date().toISOString() },
];

export const sampleProjects: Project[] = [
    {
        id: '1',
        title: 'Fit Agent: Asistente Nutricional con IA',
        slug: 'fit-agent-ia',
        description: 'Aplicacion nativa movil impulsada por inteligencia artificial para la generacion de recomendaciones nutricionales personalizadas segun el perfil fisico del usuario.',
        long_description: 'Plataforma movil integral orientada al sector fitness. Integra modelos de IA generativa para confeccionar recetas adaptadas a objetivos corporales especificos. Desarrollada para ecosistemas Android, iOS y Windows con un enfoque primordial en una experiencia de usuario fluida e intuitiva.',
        tech_stack: ['Mobile', 'AI', 'Android/iOS'],
        image_url: null,
        image_storage_path: null,
        live_url: null,
        repo_url: 'https://github.com/Nightmarespirits/fit_agent',
        sort_order: 0,
        is_visible: true,
        is_featured: true,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        title: 'Sistema de Gestion de Procesos',
        slug: 'sistema-gestion-procesos',
        description: 'Plataforma administrativa para la automatizacion y control centralizado de operaciones, optimizando el seguimiento de metricas clave y la eficiencia del negocio.',
        long_description: 'Arquitectura SPA enfocada en la modernizacion de negocios operativos. Incorpora dashboards en tiempo real, gestion de inventario, roles administrativos avanzados y un sistema agil de generacion de reportes.',
        tech_stack: ['Vue.js', 'Node.js', 'Express', 'MongoDB', 'JavaScript'],
        image_url: null,
        image_storage_path: null,
        live_url: 'https://slcdemo.netlify.app/login',
        repo_url: 'https://github.com/Nightmarespirits/slc_Gestion_Operaciones',
        sort_order: 1,
        is_visible: true,
        is_featured: true,
        created_at: '2023-01-01T00:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        title: 'Motor de Gestion de Archivos',
        slug: 'gestion-archivos',
        description: 'Solucion corporativa optimizada para el rastreo, control y distribucion segura de documentos, disenada bajo arquitecturas orientadas a micro-operaciones.',
        long_description: 'Sistema empresarial desarrollado con Spring Boot y Vue.js. Su arquitectura robusta gestiona el ciclo de vida de los activos digitales asegurando accesos controlados y operaciones automatizadas para corporaciones.',
        tech_stack: ['Vue.js', 'Java', 'Spring Boot', 'MySQL', 'Docker'],
        image_url: null,
        image_storage_path: null,
        live_url: 'https://gestorarchivos-demo.netlify.app/',
        repo_url: 'https://github.com/Nightmarespirits/Gestor_Archivos_Web',
        sort_order: 2,
        is_visible: true,
        is_featured: false,
        created_at: '2022-01-01T00:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        title: 'Handmouse CV',
        slug: 'handmouse',
        description: 'Herramienta de vision computacional que interpreta gestos manuales capturados por camara web en comandos de raton.',
        long_description: 'Desarrollada en Python utilizando OpenCV y modelos predictivos, esta aplicacion redefine la interaccion HCI con configuraciones de gestos personalizables y respuesta en tiempo real.',
        tech_stack: ['Python', 'Computer Vision', 'OpenCV', 'AI'],
        image_url: null,
        image_storage_path: null,
        live_url: 'https://github.com/fernandotutaya/handmouse',
        repo_url: 'https://github.com/fernandotutaya/handmouse',
        sort_order: 3,
        is_visible: true,
        is_featured: false,
        created_at: '2023-06-01T00:00:00Z',
        updated_at: new Date().toISOString(),
    },
];

export const sampleExperience: Experience[] = [
    {
        id: '1',
        company: 'IESTPFFAA',
        role: 'Proyectos Academicos y Finalizacion de Estudios Tecnicos',
        description: 'Culminacion de la carrera tecnica en Analisis de Sistemas. Desarrollo de arquitecturas orientadas a servicios, diseno de bases de datos relacionales y despliegue de soluciones escalables.',
        start_date: '2025-01-01',
        end_date: null,
        location: 'Lima, Peru',
        tech_used: ['Java', 'Spring Boot', 'Vue.js', 'Docker', 'Bases de Datos'],
        sort_order: 0,
        is_visible: true,
        created_at: new Date().toISOString(),
    },
    {
        id: '2',
        company: 'Programa de Practicas',
        role: 'Desarrollador Trainee',
        description: 'Participacion en celulas de desarrollo para integraciones funcionales, pruebas unitarias y optimizacion de consultas SQL.',
        start_date: '2024-01-01',
        end_date: '2024-12-31',
        location: 'Lima, Peru',
        tech_used: ['Java', 'SQL', 'Git', 'Metodologias Agiles', 'Testing'],
        sort_order: 1,
        is_visible: true,
        created_at: new Date().toISOString(),
    },
    {
        id: '3',
        company: 'Clientes Independientes',
        role: 'Desarrollador Full Stack (Freelance)',
        description: 'Toma de requerimientos, diseno UX/UI preliminar y desarrollo end-to-end de aplicaciones web a medida.',
        start_date: '2023-01-01',
        end_date: '2023-12-31',
        location: 'Remoto',
        tech_used: ['Node.js', 'Express', 'Vue.js', 'JavaScript'],
        sort_order: 2,
        is_visible: true,
        created_at: new Date().toISOString(),
    },
];

export const sampleSkills: Skill[] = [
    { id: '1', name: 'Java', category: 'Backend & Core', proficiency: 92, sort_order: 0, is_visible: true, created_at: new Date().toISOString() },
    { id: '2', name: 'Spring Boot', category: 'Backend & Core', proficiency: 88, sort_order: 1, is_visible: true, created_at: new Date().toISOString() },
    { id: '3', name: 'Node.js / Express', category: 'Backend & Core', proficiency: 85, sort_order: 2, is_visible: true, created_at: new Date().toISOString() },
    { id: '4', name: 'Arquitectura REST / Microservicios', category: 'Backend & Core', proficiency: 90, sort_order: 3, is_visible: true, created_at: new Date().toISOString() },
    { id: '5', name: 'JavaScript / ES6+', category: 'Frontend', proficiency: 88, sort_order: 0, is_visible: true, created_at: new Date().toISOString() },
    { id: '6', name: 'Vue.js', category: 'Frontend', proficiency: 85, sort_order: 1, is_visible: true, created_at: new Date().toISOString() },
    { id: '7', name: 'React / Next.js', category: 'Frontend', proficiency: 80, sort_order: 2, is_visible: true, created_at: new Date().toISOString() },
    { id: '8', name: 'CSS3 / SASS / Tailwind', category: 'Frontend', proficiency: 90, sort_order: 3, is_visible: true, created_at: new Date().toISOString() },
    { id: '9', name: 'SQL (MySQL/PostgreSQL)', category: 'Bases de Datos', proficiency: 88, sort_order: 0, is_visible: true, created_at: new Date().toISOString() },
    { id: '10', name: 'MongoDB', category: 'Bases de Datos', proficiency: 82, sort_order: 1, is_visible: true, created_at: new Date().toISOString() },
    { id: '11', name: 'Diseno ORM/ODM', category: 'Bases de Datos', proficiency: 88, sort_order: 2, is_visible: true, created_at: new Date().toISOString() },
    { id: '12', name: 'Git / GitHub Actions / CI/CD', category: 'DevOps & Herramientas', proficiency: 85, sort_order: 0, is_visible: true, created_at: new Date().toISOString() },
    { id: '13', name: 'Docker', category: 'DevOps & Herramientas', proficiency: 80, sort_order: 1, is_visible: true, created_at: new Date().toISOString() },
    { id: '14', name: 'Testing Automatizado (Jest/JUnit)', category: 'DevOps & Herramientas', proficiency: 85, sort_order: 2, is_visible: true, created_at: new Date().toISOString() },
];

export const sampleSiteTheme: SiteThemeSettings = {
    ...DEFAULT_SITE_THEME,
    updated_at: new Date().toISOString(),
};
